### ISSUE TITLE
Remove SQS logic, dependencies, and config from pages-builder

### ISSUE THREAD

**Issue by apburnes** [cloud-gov/pages-builder#537]
With the move to the Redis queue, we need to remove the AWS SQS related dependencies, configuration, and logic from the app and its deployments.

## Acceptance Criteria
* [ ] Remove the user provided services supply now deprecated SQS credentials
* [x] Remove config for SQS
* [x] Remove logic within app for SQS

--- 

## Security considerations
Needed for SCR

**Comment by apburnes** [comment]
See PR https://github.com/cloud-gov/pages-builder/pull/542

**Comment by drewbo** [comment]
Deployed and services removed
